### PR TITLE
Update build.sh

### PR DESCRIPTION
**Pull request by szhu**
fish 2.2.0

### CODE REVIEW

**Comment by szhu** [comment]
I made this edit on my phone. Are you sure it works?

**Comment by rogerhub** [comment]
how'd you do that on your phone?? impressive.

**Comment by szhu** [comment]
You just click the edit button, lol

**Comment by rogerhub** [comment]
editing text without vim is too hard

**Comment by szhu** [comment]
you're saying it's

vimpossible

**Comment by rogerhub** [comment]
...

:clap:

**Comment by szhu** [comment]
I can just vimagine you cringing rn

**Comment by rogerhub** [comment]
thanks for the patch &gt;.&gt;

**Pull request merged**
